// <auto-generated />
using System;
using KleeneStar.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KleeneStar.Model.Sqlite.Migrations
{
    [DbContext(typeof(KleeneStarDbContext))]
    partial class KleeneStarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ClassAllowedChild", b =>
                {
                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChildId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassAllowedChild");
                });

            modelBuilder.Entity("DashboardCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DashboardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "DashboardId");

                    b.HasIndex("DashboardId");

                    b.ToTable("DashboardCategory");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Category", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RawId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Class", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AccessModifier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccessModifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<Guid?>("InheritedId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Inherited");

                    b.Property<bool>("IsAbstract")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsAbstract");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Parent");

                    b.Property<bool>("Sealed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sealed");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Workspace");

                    b.HasKey("RawId");

                    b.HasIndex("InheritedId");

                    b.HasIndex("ParentId");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Dashboard", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dashboard", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.DashboardColumn", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Dashboard");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Size")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Size");

                    b.HasKey("RawId");

                    b.HasIndex("DashboardId", "Name")
                        .IsUnique();

                    b.ToTable("DashboardColumn", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Field", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AccessModifier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccessModifier");

                    b.Property<int>("Cardinality")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Cardinality");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("DefaultSpec")
                        .HasColumnType("TEXT")
                        .HasColumnName("DefaultSpec");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Deprecated");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("FieldType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("FieldType");

                    b.Property<string>("HelpText")
                        .HasColumnType("TEXT")
                        .HasColumnName("HelpText");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Placeholder");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Required");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<bool>("Unique")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Unique");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("TEXT")
                        .HasColumnName("ValidationRules");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.ToTable("Field", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Form", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<int>("FormType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FormType");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Group", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.HasKey("RawId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.GroupPolicy", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GroupId");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Policy");

                    b.HasKey("RawId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupPolicy", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Identity", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.HasKey("RawId");

                    b.ToTable("Identity", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.IdentityGroupMembership", b =>
                {
                    b.Property<int>("IdentityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdentityId");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GroupId");

                    b.HasKey("IdentityId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("IdentityGroupMembership", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Object", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Summary");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Workspace");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Object", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Priority", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.ToTable("Priority", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Status", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<int?>("WorkflowRawId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RawId");

                    b.HasIndex("WorkflowRawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Name", "ClassId")
                        .IsUnique();

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.StatusCategory", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Color")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.ToTable("StatusCategory", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Tenant", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.HasKey("RawId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Transition", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Workflow");

                    b.HasKey("RawId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.HasIndex("WorkflowId", "Name")
                        .IsUnique();

                    b.ToTable("Transition", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Widget", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Column");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Wql")
                        .HasColumnType("TEXT")
                        .HasColumnName("Wql");

                    b.HasKey("RawId");

                    b.HasIndex("ColumnId", "Name")
                        .IsUnique();

                    b.ToTable("Widget", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workflow", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workspace", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AccessModifier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccessModifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<Guid?>("InheritedId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Inherited");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<bool>("Sealed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sealed");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("InheritedId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workspace", (string)null);
                });

            modelBuilder.Entity("WorkspaceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceCategory");
                });

            modelBuilder.Entity("WorkspaceTenant", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TenantId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceTenant");
                });

            modelBuilder.Entity("ClassAllowedChild", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DashboardCategory", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Dashboard", null)
                        .WithMany()
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Class", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Inherited")
                        .WithMany()
                        .HasForeignKey("InheritedId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KleeneStar.Model.Entities.Class", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KleeneStar.Model.Entities.Workspace", "Workspace")
                        .WithMany("Classes")
                        .HasForeignKey("WorkspaceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inherited");

                    b.Navigation("Parent");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.DashboardColumn", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Dashboard", "Dashboard")
                        .WithMany("Columns")
                        .HasForeignKey("DashboardId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dashboard");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Field", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Form", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.GroupPolicy", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Group", "Group")
                        .WithMany("GroupPolicies")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.IdentityGroupMembership", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Group", "Group")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Identity", "Identity")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Object", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workspace", "Workspace")
                        .WithMany("Objects")
                        .HasForeignKey("WorkspaceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Priority", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Status", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.StatusCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workflow", null)
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowRawId");

                    b.Navigation("Category");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Transition", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Status", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Status", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workflow", "Workflow")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Widget", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.DashboardColumn", "Column")
                        .WithMany("Widgets")
                        .HasForeignKey("ColumnId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workflow", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workspace", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Workspace", "Inherited")
                        .WithMany()
                        .HasForeignKey("InheritedId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Inherited");
                });

            modelBuilder.Entity("WorkspaceCategory", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkspaceTenant", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Dashboard", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.DashboardColumn", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Group", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("GroupPolicies");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Identity", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workflow", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workspace", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
