// <auto-generated />
using System;
using KleeneStar.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KleeneStar.Model.Sqlite.Migrations
{
    [DbContext(typeof(KleeneStarDbContext))]
    partial class KleeneStarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("KleeneStar.Model.Entities.Category", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RawId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Class", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Workspace");

                    b.HasKey("RawId");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Field", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.ToTable("Field", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Object", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Summary");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Workspace");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Object", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Priority", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Class");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique();

                    b.ToTable("Priority", (string)null);
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Workspace", b =>
                {
                    b.Property<int>("RawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Icon");

                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated");

                    b.HasKey("RawId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workspace", (string)null);
                });

            modelBuilder.Entity("WorkspaceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceCategory");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Class", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Field", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Object", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KleeneStar.Model.Entities.Priority", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("WorkspaceCategory", b =>
                {
                    b.HasOne("KleeneStar.Model.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KleeneStar.Model.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
